### PR TITLE
[German] Languages

### PR DESCRIPTION
**Pull request by Aetherya**
Translated ALL Strings of the language file into German, opened up German folder, copied all files over

### CODE REVIEW

**Comment by deB4SH** [comment]
Hey @AriaHoshiine please rename the folder to de/ instead of /ger.
From my side the language terms looks nice. 👍 

Waiting for approval from @hboelke

**Review by deB4SH — DISMISSED** [review]
first looks seems ok

**Comment by hboelke** [comment]
@AriaHoshiine please Change the translations for 
`` Azerbaijani `` to `` Aserbaidschanisch ``
`` Afrikaans `` to ``Afrikaans `` 
``Khmer`` to `` Kambodschanisch `` 
``Swedish`` to ``Schwedisch`` 

Everything else looks good for me.

**Review by hboelke — APPROVED** [review]
Looks good for me now.

**Review by deB4SH — APPROVED** [review]
approved also from my side

**Comment by deB4SH** [comment]
merging it into master @aziznatour

**Pull request merged**
